[package]
name = "neura-gpu"
version.workspace = true
edition.workspace = true
description = "Native compute devices, memory, pipelines and submissions"
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
bitflags = { workspace = true }
neura-compiler = { workspace = true }

[dev-dependencies]
bytemuck = { workspace = true }
pollster = { workspace = true }

[target.'cfg(any(target_os = "windows", target_os = "linux", target_os = "macos"))'.dependencies]
ash = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
libloading = { workspace = true }
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D_Dxc",
    "Win32_Graphics_Direct3D12",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_System_Threading",
] }

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = { workspace = true }
objc2-foundation = { workspace = true, features = ["NSArray", "NSError", "NSString"] }
objc2-metal = { workspace = true, features = [
    "MTLAllocation",
    "MTLBlitCommandEncoder",
    "MTLBuffer",
    "MTLCommandBuffer",
    "MTLCommandEncoder",
    "MTLCommandQueue",
    "MTLComputeCommandEncoder",
    "MTLComputePipeline",
    "MTLDevice",
    "MTLLibrary",
    "MTLResource",
    "MTLTypes",
] }
